name: Python CI with Poetry

on:
  pull_request: # Se déclenche à chaque PR, peu importe la branche
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry to disable virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry add --dev flake8 black pytest coverage isort

      - name: Lint with isort
        run: |
          poetry run isort . --check-only --diff

      - name: Lint with black
        run: |
          poetry run black --check .

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run tests and generate coverage report
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage xml
          poetry run coverage html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/
